// Generated by Cadence Genus(TM) Synthesis Solution 16.13-s036_1 
// Generated on: Dec  6 2024 14:29:00 BDT (Dec  6 2024 08:29:00 UTC) 
// Verification Directory fv/SISO_FIFO_ShiftRegister  
module SISO_FIFO_ShiftRegister(Clk, Load, Left, Din, A, Dout, register); 
input Clk, Load, Left, Din; 
input [15:0] A; 
output Dout; 
output [15:0] register; 
wire Clk, Load, Left, Din; 
wire [15:0] A; 
wire Dout; 
wire [15:0] register; 
wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7; 
wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15; 
wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23; 
wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31; 
wire n_32, n_33, n_34, n_35; 
DFFHQX1 Dout_reg(.CK (Clk), .D (n_35), .Q (Dout)); 

DFFHQX1 \register_reg[14] (.CK (Clk), .D (n_34), .Q (register[14])); 
OAI2BB1X1 g747(.A0N (n_32), .A1N (register[0]), .B0 (n_31), .Y 
(n_35)); 
OAI2BB1X1 g748(.A0N (n_30), .A1N (register[13]), .B0 (n_33), .Y 
(n_34)); 
AOI22XL g749(.A0 (n_32), .A1 (register[15]), .B0 (Load), .B1 (A[14]), 
.Y (n_33)); 
AOI22XL g750(.A0 (n_30), .A1 (register[15]), .B0 (Load), .B1 (Dout), 
.Y (n_31)); 
DFFHQX1 \register_reg[13] (.CK (Clk), .D (n_17), .Q (register[13])); 
DFFHQX1 \register_reg[6] (.CK (Clk), .D (n_21), .Q (register[6])); 
DFFHQX1 \register_reg[2] (.CK (Clk), .D (n_28), .Q (register[2])); 
DFFHQX1 \register_reg[3] (.CK (Clk), .D (n_20), .Q (register[3])); 
DFFHQX1 \register_reg[4] (.CK (Clk), .D (n_18), .Q (register[4])); 
DFFHQX1 \register_reg[5] (.CK (Clk), .D (n_22), .Q (register[5])); 
DFFHQX1 \register_reg[10] (.CK (Clk), .D (n_25), .Q (register[10])); 
DFFHQX1 \register_reg[7] (.CK (Clk), .D (n_16), .Q (register[7])); 
DFFHQX1 \register_reg[0] (.CK (Clk), .D (n_24), .Q (register[0])); 
DFFHQX1 \register_reg[8] (.CK (Clk), .D (n_23), .Q (register[8])); 
DFFHQX1 \register_reg[9] (.CK (Clk), .D (n_26), .Q (register[9])); 
DFFHQX1 \register_reg[1] (.CK (Clk), .D (n_27), .Q (register[1])); 
DFFHQX1 \register_reg[11] (.CK (Clk), .D (n_29), .Q (register[11])); 
DFFHQX1 \register_reg[12] (.CK (Clk), .D (n_15), .Q (register[12])); 
DFFHQX1 \register_reg[15] (.CK (Clk), .D (n_19), .Q (register[15])); 
INVXL g782(.A (n_8), .Y (n_29)); 
INVXL g777(.A (n_6), .Y (n_28)); 
INVXL g778(.A (n_14), .Y (n_27)); 
INVXL g779(.A (n_12), .Y (n_26)); 
INVXL g780(.A (n_11), .Y (n_25)); 
INVXL g766(.A (n_13), .Y (n_24)); 
INVXL g781(.A (n_10), .Y (n_23)); 

OAI2BB1X1 g773(.A0N (n_30), .A1N (register[4]), .B0 (n_1), .Y (n_22)); 
INVXL g768(.A (n_4), .Y (n_21)); 
INVXL g769(.A (n_3), .Y (n_20)); 
OAI2BB1X1 g771(.A0N (n_30), .A1N (register[14]), .B0 (n_2), .Y 
(n_19)); 
INVXL g767(.A (n_9), .Y (n_18)); 
INVXL g784(.A (n_5), .Y (n_17)); 
OAI2BB1X1 g775(.A0N (n_30), .A1N (register[6]), .B0 (n_0), .Y (n_16)); 
INVXL g783(.A (n_7), .Y (n_15)); 
AOI222X1 g786(.A0 (Load), .A1 (A[1]), .B0 (n_32), .B1 (register[2]), 
.C0 (n_30), .C1 (register[0]), .Y (n_14)); 
AOI222X1 g770(.A0 (Load), .A1 (A[0]), .B0 (n_32), .B1 (register[1]), 
.C0 (Din), .C1 (n_30), .Y (n_13)); 
AOI222X1 g787(.A0 (Load), .A1 (A[9]), .B0 (n_32), .B1 (register[10]), 
.C0 (n_30), .C1 (register[8]), .Y (n_12)); 
AOI222X1 g788(.A0 (Load), .A1 (A[10]), .B0 (n_32), .B1 
(register[11]), .C0 (n_30), .C1 (register[9]), .Y (n_11)); 
AOI222X1 g789(.A0 (Load), .A1 (A[8]), .B0 (n_32), .B1 (register[9]), 
.C0 (n_30), .C1 (register[7]), .Y (n_10)); 
AOI222X1 g772(.A0 (Load), .A1 (A[4]), .B0 (n_32), .B1 (register[5]), 
.C0 (n_30), .C1 (register[3]), .Y (n_9)); 
AOI222X1 g790(.A0 (Load), .A1 (A[11]), .B0 (n_32), .B1 
(register[12]), .C0 (n_30), .C1 (register[10]), .Y (n_8)); 
AOI222X1 g791(.A0 (Load), .A1 (A[12]), .B0 (n_32), .B1 
(register[13]), .C0 (n_30), .C1 (register[11]), .Y (n_7)); 
AOI222X1 g785(.A0 (Load), .A1 (A[2]), .B0 (n_32), .B1 (register[3]), 
.C0 (n_30), .C1 (register[1]), .Y (n_6)); 
AOI222X1 g792(.A0 (Load), .A1 (A[13]), .B0 (n_32), .B1 
(register[14]), .C0 (n_30), .C1 (register[12]), .Y (n_5)); 
AOI222X1 g774(.A0 (Load), .A1 (A[6]), .B0 (n_32), .B1 (register[7]), 
.C0 (n_30), .C1 (register[5]), .Y (n_4)); 

AOI222X1 g776(.A0 (Load), .A1 (A[3]), .B0 (n_32), .B1 (register[4]), 
.C0 (n_30), .C1 (register[2]), .Y (n_3)); 
AOI22XL g793(.A0 (Din), .A1 (n_32), .B0 (Load), .B1 (A[15]), .Y 
(n_2)); 
AOI22XL g794(.A0 (n_32), .A1 (register[6]), .B0 (Load), .B1 (A[5]), 
.Y (n_1)); 
AOI22XL g795(.A0 (n_32), .A1 (register[8]), .B0 (Load), .B1 (A[7]), 
.Y (n_0)); 
NOR2X1 g796(.A (Left), .B (Load), .Y (n_32)); 
NOR2BX1 g797(.AN (Left), .B (Load), .Y (n_30)); 
Endmodule
